### 1. 유저 가입/로그인
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "name": "원영",
  "socialId": "kakao_12345",
  "provider": "kakao"
}

### 2. 로그아웃 
POST http://localhost:3000/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzb2NpYWxJZCI6IjExNzM1MDEwMzc1MDgzMzE5NzkzMCIsInByb3ZpZGVyIjoiZ29vZ2xlIiwic3ViIjo1LCJpYXQiOjE3NzM2NDY3NDUsImV4cCI6MTc3MzY0NzY0NX0.sqoTybEK7JsrZYWmxJrDOGyN4S_vIs8JrGn-KzbR2pE